

import user from '../../images/user.png';
import save from '../../images/save.png';
import camera from '../../images/camera.webp';
import folder from '../../images/folder.jpeg';
import pic from '../../images/pic.png';
import ImageOutlinedIcon from '@mui/icons-material/ImageOutlined';
import ArticleOutlinedIcon from '@mui/icons-material/ArticleOutlined';
import EventIcon from '@mui/icons-material/Event';


export type postType={
    id: number,
    thumbnail: string,
    videotitle: string,
    username: string,
    uploaddate: Date ,
    view: number,
    comment: number,
    like: number,
    category:string,
    subject:string,
    primer:string,
    newhushtag:string,
    hushtag:string,
    level1:string,
    level2:string,
    level3:string,
    level4:string,
    level5:string,
    level6:string,
  }
  
export const PostData = [
    {
        id: 1,
        thumbnail: "https://www.youtube.com/watch?v=oytujBoPHR0",
        videotitle: "Gameing",
        username: "Belline",
        uploaddate: Date() ,
        view: 34,
        comment: 23,
        like: 30,
        category:'',
        subject:'',
        primer:'',
        newhushtag:'',
        hushtag:'',
        level1:'',
        level2:'',
        level3:'',
        level4:'',
        level5:'',
        level6:'',
    },
    {
        id: 2,
        thumbnail: "https://www.twitch.tv/videos/1649911169?collection=qzkA5KtaBxfk1w",
        videotitle: "Live Seesion",
        username: "Leanne Graham",
        uploaddate: Date() ,
        view: 120345,
        comment: 22303,
        like: 67584,
        category:'',
        subject:'',
        primer:'',
        newhushtag:'',
        hushtag:'',
        level1:'',
        level2:'',
        level3:'',
        level4:'',
        level5:'',
        level6:'',
    },
    {
        id: 3,
        thumbnail: "https://www.youtube.com/watch?v=eIHKZfgddLM",
        videotitle: "Dot Net video",
        username: "Zenawit",
        uploaddate: Date() ,
        view: 231,
        comment: 293,
        like: 1294,
        category:'',
        subject:'',
        primer:'',
        newhushtag:'',
        hushtag:'',
        level1:'',
        level2:'',
        level3:'',
        level4:'',
        level5:'',
        level6:'',
    },
    {
        id: 4,
        thumbnail: "https://www.youtube.com/watch?v=eIHKZfgddLM",
        videotitle: "Kids Musics",
        username: "Lemma",
        uploaddate: Date() ,
        view: 2567,
        comment: 456,
        like: 9056,
        category:'',
        subject:'',
        primer:'',
        newhushtag:'',
        hushtag:'',
        level1:'',
        level2:'',
        level3:'',
        level4:'',
        level5:'',
        level6:'',
    },
    // {
    //     id: 5,
    //     thumbnail: "https://www.twitch.tv/videos/1679924557?collection=ryMlWIJaBxf2aQ",
    //     videotitle: "Chatting Session",
    //     username: "Selam Tekle",
    //     uploaddate: Date() ,
    //     view: 200,
    //     comment: 20,
    //     like: 1230,
    //     category:'',
    //     subject:'',
    //     primer:'',
    //     newhushtag:'',
    //     hushtag:'',
    //     level1:'',
    //     level2:'',
    //     level3:'',
    //     level4:'',
    //     level5:'',
    //     level6:'',
    // },
    // {
    //     id: 7,
    //     thumbnail: "https://www.youtube.com/watch?v=otRv-czAq4c",
    //     videotitle: "Daily Show ",
    //     username: "Blen Goblel",
    //     uploaddate: Date() ,
    //     view: 897,
    //     comment: 40,
    //     like: 405,
    //     category:'',
    //     subject:'',
    //     primer:'',
    //     newhushtag:'',
    //     hushtag:'',
    //     level1:'',
    //     level2:'',
    //     level3:'',
    //     level4:'',
    //     level5:'',
    //     level6:'',
    // },
    // {
    //     id: 8,
    //     thumbnail: "https://www.youtube.com/watch?v=mYtl4t6Kf5Q",
    //     videotitle: "Music",
    //     username: "Tommy Dann",
    //     uploaddate: Date() ,
    //     view: 236,
    //     comment: 6,
    //     like: 78,
    //     category:'',
    //     subject:'',
    //     primer:'',
    //     newhushtag:'',
    //     hushtag:'',
    //     level1:'',
    //     level2:'',
    //     level3:'',
    //     level4:'',
    //     level5:'',
    //     level6:'',
    // },
  ];
  export const SummaryCards = [
    { id:4, title:"text" ,data:"4 hundred" , icon:EventIcon, image:pic , color:'green' },
    { id:5, title:"text" ,data:"60 Million" , icon:ArticleOutlinedIcon, image:user , color:'green' },
    { id:6, title:"text" ,data:"3.2 Thausand" , icon:ImageOutlinedIcon, image:folder , color:'green' }
 ];
export const Columns=[
    { Header : 'Id' , accessor: 'id' },
    { Header : 'Thumbnail' , accessor: 'thumbnail' },
    { Header : 'Video Title' , accessor: 'videotitle' },
    { Header : 'User Name' , accessor: 'username' },
    { Header : 'Upload Date' , accessor: 'uploaddate' },
    { Header : 'View' , accessor: 'view' },
    { Header : 'Comment' , accessor: 'comment' },
    { Header : 'Like' , accessor: 'like' }
]
